# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./ 
COPY planetData.json ./

# Install application dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the port your Express.js application listens on
EXPOSE 4000
EXPOSE 3306

# Define the command to start your application
CMD ["node", "index.js"]
